AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "tmp/**/*"
    - ".git/**/*"
    - "bin/*"
  TargetRubyVersion: 2.6
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
